### ISSUE TITLE
Mouseup event should also be unbinded after it is fired

### ISSUE THREAD

**Issue by jeremy-dimasuay** [cmaish/DragSort#2]
```
$(list.container).mousemove(trigger).mouseup(function() { $(list.container).unbind("mousemove", trigger); $(dragHandle).css("cursor", $(dragHandle).attr("data-cursor")); });
```

Currently every time a user grabs an item (aka function grabItem()), a mouseup event is binded.  However I believe this mouseup event needs to be unbinded after firing (similar how you already do it during the mousemove event).

**Comment by cmaish** [comment]
Hi @jeremy-dimasuay,

First up, thanks for the issue report.  http://dragsort.codeplex.com/workitem/list/basic is probably a better place to report this - my fork is (relatively) static and was just made to add the dragstart event which was necessary for my use.  I'll pull new versions down from there from time to time to resolve issues, but I'm not actively developing on this project.

**Comment by jeremy-dimasuay** [comment]
Thanks @cmaish for the reply.

I found the dragstart event to be useful too.  Regardless, I appreciate your work.  I'll find you on codeplex if I find anymore issues.
